import { registry } from './registry';
import mountains from './mountains';
import gradient from './gradient';
import waves from './waves';
import paper from './paper';
import rings from './rings';
import chaos from './chaos';
import dunes from './dunes';
import aurora from './aurora';
import contours from './contours';
import horizon from './horizon';
import fog from './fog';
import hills from './hills';
import orbit from './orbit';

registry.register(mountains);
registry.register(gradient);
registry.register(waves);
registry.register(paper);
registry.register(rings);
registry.register(chaos);
registry.register(dunes);
registry.register(aurora);
registry.register(contours);
registry.register(horizon);
registry.register(fog);
registry.register(hills);
registry.register(orbit);

export { registry };
export type { StyleDefinition, StyleParams } from './types';
